const ScreenConst = {
  introSlider: 'INTRO_SLIDER',
  home: 'Home',
  SignUp: 'SignUp',
  FAQs: 'FAQs',
  drawer: 'Drawer',
  selectLanguage: 'SELECT_LANGUAGE',
  verificationCode: 'VERIFICATION_CODE',
  login: 'LOGIN',
  itemDetails: 'ITEM_DETAILS',
  filter: 'Filter',
  allCategories: 'ALL_CATEGORIES',
  addToCart: 'ADD_TO_CART',
  promo: 'PROMO',
  shop: 'Shop',
  userProfile: 'USER_PROFILE',
  notification: 'NOTIFICATIONS',
  allProducts: 'ALL_PRODUCTS',
  orderStatus: 'ORDER_STATUS',
  trackOrder: 'Track_Order',
  thankYou: 'Thank_You',
  cartDetails: 'Cart_Detail',
  viewCart: 'View_Cart',
  selectAddress: 'Select_Address',
  allAddresses: 'ALL_ADDRESS_SCREEN',
  customerSupport: 'Customer_Support',
  searchPlacess: 'Search_Placess',
  myAccount: 'My_Account',
  promotionSupport: 'Promotion_Support',
  makingPaymentSupport: 'Making_Payment_Support',
  FAQSupport: 'Faq_Support',
  makingSupportRequest: 'Making_Support_Request',
  mySupportTickets: 'My_Support_Tickets',
  updateAccountInfo: 'Update_Account_Info',
  OtpCodeDidntWork: 'otp_code_didnt_work',
  cantSignUp: 'i_cant_signup',
  canIUseOtherNumber: 'can_i_use_other_number',
  AddOrDeletePaymentMethod: 'add_or_delete_payment_method',
  MyPaymentWasDeclined: 'my_payment_was_declined',
  CheckoutButtonDoesntWork: 'check_out_button_dosnt_work',
  PaymentMethodsAvailable: 'payment_methods_available',
  WhatIsPickup: 'what_is_pickup',
  CantEnterMyAddress: 'cant_enter_my_address',
  OrderOnMultipleRestaurants: 'order_on_multiple_restaurants',
  WillMealsBeLabelled: 'will_meals_be_labelled',
  selectBranch: 'Select_Branch',
  selectOption: 'Select_Option',
  profile: 'Profile',
  subCategories: 'Sub_Categories',
  orderDetails: 'Order_Details',
  DidntRecievePromoCode:'didnt_recieve_promo_code',
  DidntGetMyPromoDiscount:'didnt_get_my_promo_discount',
  HowNextPromoWillCome: 'how_next_promo_will_come',
  Combos: 'Combos',

};

export default ScreenConst;
