export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_HAS_SEEN_INTRO = 'SET_USER_HAS_SEEN_INTRO';
export const SET_USERS_HAS_SELECTED_LANGUAGE =
  'SET_USERS_HAS_SELECTED_LANGUAGE';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_BRANCH = 'SET_BRANCH';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const SET_OPTION = 'SET_OPTION';
export const SET_NOTIFICATION_TOKEN = 'SET_NOTIFICATION_TOKEN';
export const SET_NOTIFICATION_COUNT = 'SET_NOTIFICATION_COUNT';
export const INCREMENT_NOTIFICATION_COUNT = 'INCREMENT_NOTIFICATION_COUNT';
